#!/usr/bin/env bun
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import data from "unicode-emoji-json/data-by-emoji.json" with { type: "json" };

interface EmojiMeta {
  slug: string;
}
const source = data as Record<string, EmojiMeta>;

const LEADING_DIGIT = /^[0-9]/;
const NON_WORD_RUN = /[^a-z0-9]+([a-z0-9])/g;
const NON_WORD_CHAR = /[^a-zA-Z0-9]/g;

const RESERVED: ReadonlySet<string> = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "let",
  "static",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
]);

const toCamel = (slug: string): string => {
  const camel = slug
    .toLowerCase()
    .replace(NON_WORD_RUN, (_, c: string) => c.toUpperCase())
    .replace(NON_WORD_CHAR, "");
  const safe = LEADING_DIGIT.test(camel) ? `_${camel}` : camel;
  return RESERVED.has(safe) ? `${safe}_` : safe;
};

const entries = new Map<string, string>();
for (const [emoji, meta] of Object.entries(source)) {
  const key = toCamel(meta.slug);
  if (!entries.has(key)) {
    entries.set(key, emoji);
  }
}

const sorted = [...entries.entries()].sort(([a], [b]) => a.localeCompare(b));

const body = [
  "// AUTO-GENERATED by scripts/generate-emoji.ts — do not edit by hand.",
  "// Regenerate with: bun run generate:emoji",
  "",
  "export const GeneratedEmoji = {",
  ...sorted.map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`),
  "} as const;",
  "",
  "export type GeneratedEmojiKey = keyof typeof GeneratedEmoji;",
  "",
].join("\n");

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "..", "src", "emoji", "generated.ts");
writeFileSync(outPath, body);

console.log(`Wrote ${entries.size} emoji to ${outPath}`);
