// This file is generated by scripts/prepare-package.ts. Do not edit.
//
// Locally and during `bun run build` this file reads:
//   SPECTRUM_SDK_VERSION = "local"
//   SPECTRUM_BUILD_ENV   = "development"
// The release workflow builds with SPECTRUM_PUBLISH=1, which stamps the real
// package.json#version and "production" instead.
export const SPECTRUM_SDK_VERSION = "local";
export const SPECTRUM_BUILD_ENV: "development" | "production" = "development";
