// This file is generated by scripts/prepare-package.ts. Do not edit.
//
// Locally and during `bun run build` this file reads:
//   SPECTRUM_SDK_VERSION = "local"
//   SPECTRUM_BUILD_ENV   = "development"
// The `prepack` script (run by `bun publish`) overwrites both with the real
// package.json#version and "production" before tsup compiles, then resets
// them back so the working tree stays clean.
export const SPECTRUM_SDK_VERSION = "local";
export const SPECTRUM_BUILD_ENV: "development" | "production" = "development";
