#!/usr/bin/env bun
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { file, write } from "bun";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const repoRoot = join(packageRoot, "..", "..");

const pkg = (await file(join(packageRoot, "package.json")).json()) as {
  version: string;
};

// Publish builds are selected via env (set by the release workflow), not a
// CLI flag: `clean-publish` strips `scripts` before `npm publish` runs in its
// temp dir, so a `prepack` hook never fires on publish — an env-driven build
// is the only path that reliably stamps the real version into the artifact.
// SPECTRUM_PUBLISH is declared in turbo.json's `env` so the publish job can
// never be served a cached development-mode build.
const publishing = process.env.SPECTRUM_PUBLISH === "1";
const buildEnv: "development" | "production" = publishing
  ? "production"
  : "development";
const sdkVersion = publishing ? pkg.version : "local";

const buildEnvFile = `// This file is generated by scripts/prepare-package.ts. Do not edit.
//
// Locally and during \`bun run build\` this file reads:
//   SPECTRUM_SDK_VERSION = "local"
//   SPECTRUM_BUILD_ENV   = "development"
// The release workflow builds with SPECTRUM_PUBLISH=1, which stamps the real
// package.json#version and "production" instead.
export const SPECTRUM_SDK_VERSION = "${sdkVersion}";
export const SPECTRUM_BUILD_ENV: "development" | "production" = "${buildEnv}";
`;

await write(join(packageRoot, "src/build-env.ts"), buildEnvFile);
await write(join(packageRoot, "README.md"), file(join(repoRoot, "README.md")));
await write(join(packageRoot, "LICENSE"), file(join(repoRoot, "LICENSE")));

console.log(`Prepared spectrum-ts v${sdkVersion} (env=${buildEnv})`);
