#!/usr/bin/env bun
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const repoRoot = join(packageRoot, "..", "..");

const pkg = JSON.parse(
  await readFile(join(packageRoot, "package.json"), "utf8")
) as {
  version: string;
};

const publishing = process.argv.includes("--publish");
const buildEnv: "development" | "production" = publishing
  ? "production"
  : "development";
const sdkVersion = publishing ? pkg.version : "local";

const buildEnvFile = `// This file is generated by scripts/prepare-package.ts. Do not edit.
//
// Locally and during \`bun run build\` this file reads:
//   SPECTRUM_SDK_VERSION = "local"
//   SPECTRUM_BUILD_ENV   = "development"
// The \`prepack\` script (run by \`bun publish\`) overwrites both with the real
// package.json#version and "production" before tsup compiles, then resets
// them back so the working tree stays clean.
export const SPECTRUM_SDK_VERSION = "${sdkVersion}";
export const SPECTRUM_BUILD_ENV: "development" | "production" = "${buildEnv}";
`;

await writeFile(join(packageRoot, "src/build-env.ts"), buildEnvFile);
await writeFile(
  join(packageRoot, "README.md"),
  await readFile(join(repoRoot, "README.md"), "utf8")
);
await writeFile(
  join(packageRoot, "LICENSE"),
  await readFile(join(repoRoot, "LICENSE"), "utf8")
);

console.log(`Prepared spectrum-ts v${sdkVersion} (env=${buildEnv})`);
