#!/usr/bin/env bun
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const repoRoot = join(packageRoot, "..", "..");

const pkg = (await Bun.file(join(packageRoot, "package.json")).json()) as {
  version: string;
};

const versionFile = `// This file is generated by scripts/prepare-package.ts.
// Do not edit by hand — update package.json#version instead.
export const SPECTRUM_SDK_VERSION = "${pkg.version}";
`;

await Bun.write(join(packageRoot, "src/version.ts"), versionFile);
await Bun.write(
  join(packageRoot, "README.md"),
  Bun.file(join(repoRoot, "README.md"))
);
await Bun.write(
  join(packageRoot, "LICENSE"),
  Bun.file(join(repoRoot, "LICENSE"))
);

console.log(`Prepared spectrum-ts v${pkg.version}`);
